### ISSUE TITLE
Plans for a new pypi release?

### ISSUE THREAD

**Issue by m-martinez** [repoze/repoze.who#20]
Greetings!  I was wondering if there were plans to do a version bump on pypi containing  the recent changes to auth_tkt and userdata (#18)? 

Thanks!

**Comment by tseaver** [comment]
I'm working to get a 2.3 release out this weekend.

**Comment by m-martinez** [comment]
Excellent, thank you!

**Comment by tseaver** [comment]
https://pypi.python.org/pypi/repoze.who/2.3
