### ISSUE TITLE
Repoze.API.forget() won't block remember calls when used as middleware

### ISSUE THREAD

**Issue by ikelos** [repoze/repoze.who#21]
As best I can tell from [1], the identity variable passed to api.remember() is the one from the api.authenticate() call that happened on the ingress path of the request.  This means that if the underlying app calls api.logout(), even though the environ's repoze.who.identity entry is deleted, the remember call still gets provided the original identity.

At the moment I'm having to add a check in remember() to see if the environ's repoze.who.identity is set and do nothing if it's not (since we should be authenticated and that variable populated by then).  Am I missing something, or am I not using the middleware in the right way?

The fix looks like it would be to not pass identity on the line at 117, which will then get picked up from the environ instead in the api's remember call.

Happy to provide further information if it will help in any way?

[1] https://github.com/repoze/repoze.who/blob/master/repoze/who/middleware.py#L117

**Comment by tseaver** [comment]
Thanks for the report.  I believe your analysis is correct, and that we should not be passing in the originally-extracted `identity` to `api.remember()` during egress.
