### ISSUE TITLE
auth_tkt only supports MD5 checksums

### ISSUE THREAD

**Issue by lod** [repoze/repoze.who#22]
The auth_tkt standard uses a checksum to ensure the integrity of the cookie. Originally this was defined as MD5 but has since been modified to allow SHA256 and SHA512 hashes.

paste auth_tkt, upon whose implementation repoze is based have updated their code to support these other hashes.
https://bitbucket.org/ianb/paste/pull-requests/8/auth-auth_tktpy-enable-overriding-digest/diff

**Comment by frostyfrog** [comment]
I would just like to note that, in CentOS 6, repoze.who uses paste.auth_tkt with SHA256 (configurable) and CentOS 7 uses MD5 (hard-coded). A big step backwards in my opinion :frowning:

**Comment by tseaver** [comment]
@lod I would be willing to review a PR which applied a similar diff to `repoze.who._authtkt`.

@frostyfrog I'm afraid I don't have any visibility into how RedHat is packaging `repoze.who`.

**Comment by frostyfrog** [comment]
Ping. Hopefully that PR looks good. Travis says that it failed, but that was because pip was having issues in python 3.2.

**Comment by tseaver** [comment]
Closed via my merge of @lod's branch via #24.
