### ISSUE TITLE
ModuleNotFoundError: No module named 'crypt'

### ISSUE THREAD

**Issue by ondrejj** [repoze/repoze.who#44]
Hello. In python 3.13, crypt module has been removeed. In python 3.12 it's deprecated.

```
Traceback (most recent call last):                                              
  File "/builddir/build/BUILD/python-repoze-who-3.0.0-build/repoze.who-3.0.0/rep
oze/who/plugins/tests/test_htpasswd.py", line 116, in test_crypt_check          
    from crypt import crypt                                                     
ModuleNotFoundError: No module named 'crypt'
```

**Comment by mauritsvanrees** [comment]
@ondrejj I made a PR to fix this:
https://github.com/repoze/repoze.who/pull/45

I thought I had write access to this repo, but apparently not, so I did it on a fork.

**Comment by tseaver** [comment]
We need to actually replace the use of `crypt`, at least as an option, and suggest that option in the example middleware config.

**Comment by tseaver** [comment]
Per this [Apache 2.4 docs](https://httpd.apache.org/docs/2.4/misc/password_encryptions.html), we should likely be adding support for passwords encrypted using `brcrypt`'s Blowfish algorithm.  Candidates:

- https://pypi.org/project/blowfish/
- https://pypi.org/project/bcrypt/ (I can't tell at the moment whether it can be used to check Passwords encrypted via Apache's `htpasswd -nbB`.
